import ProviderWrapper from "@/blocks/commons/ProviderWrapper";
import { Metadata } from "next";
import localFont from "next/font/local";
import { Suspense } from "react";
import "./globals.css";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  // variable: "--font-pretendard",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.className} relative min-h-[calc(100dvh-3.75rem)] antialiased`}>
        <Suspense>
          <ProviderWrapper>{children}</ProviderWrapper>
        </Suspense>
      </body>
    </html>
  );
}
